Part 1: Japanese Character Recognition

1.
[[766.   7.   8.   4.  59.   8.   5.  16.  11.   8.]

 [  5. 667.  60.  40.  51.  27.  21.  29.  36.  51.]
 
 [ 10. 107. 688.  57.  79. 119. 144.  25.  95.  86.]
 
 [ 12.  18.  27. 755.  22.  17.  10.  12.  38.   3.]
 
 [ 29.  31.  27.  16. 623.  19.  26.  86.   8.  54.]
 
 [ 64.  23.  20.  59.  21. 728.  25.  17.  30.  32.]
 
 [  2.  57.  46.  13.  33.  29. 723.  53.  45.  19.]
 
 [ 63.  15.  38.  17.  35.   8.  20. 623.   7.  30.]
 
 [ 31.  25.  47.  28.  20.  33.  11.  90. 706.  39.]
 
 [ 18.  50.  39.  11.  57.  12.  15.  49.  24. 678.]]

Test set: Average loss: 1.0085, Accuracy: 6957/10000 (70%)

2. 
80 hidden node gets and accuracy of 84%. Then the increase slows down. The highest accuracy was 85% with 120 hidden nodes. 

[[859.   4.   8.   5.  49.  11.   3.  12.   9.   4.]
 
 [  4. 815.  15.   9.  27.  11.  13.  10.  27.  16.]
 
 [  3.  39. 838.  23.  19.  71.  50.  18.  24.  35.]
 
 [  5.   2.  29. 920.   7.   9.   7.   1.  44.   4.]
 
 [ 25.  19.  15.   1. 795.  10.  16.  30.   3.  25.]
 
 [ 24.   9.  19.  13.   8. 837.   8.  10.  13.  10.]
 
 [  4.  59.  25.   6.  34.  24. 888.  32.  32.  26.]
 
 [ 41.   7.  13.   2.  19.   3.   7. 819.   6.  16.]
 
 [ 28.  21.  21.   8.  21.  15.   1.  30. 832.  11.]

 [  7.  25.  17.  13.  21.   9.   7.  38.  10. 853.]]

Test set: Average loss: 0.5209, Accuracy: 8456/10000 (85%)

3. 
The parameter I used are as below:
mom = 0.9
lr = 0.01

I also used two convolutional layers. The first one has 6 channels with kernel size = 5. 

self.conv1 = nn.Conv2d(1, 6, 5)
self.conv2 = nn.Conv2d(6, 12, 5)
self.fc1 = nn.Linear(4800, 400)
self.fc2 = nn.Linear(400, 10)

It reached 94% at the 5th epoch.

4.a 

The accuracy of the three models are 70%, 85 and 94%. It is believed that the reason of such variation is related with the complexity of each model.

Firstly, the linear model has the lowest accuracy of 70%. While having the simplest structure, its accuracy stopped improving during the training. It is an indication of its overly simplified structure is struggling to meet the demand of the task. 

Seconly, the Full model reached an accuracy of 83% with 80 hidden node. It reached 85% with 120 hidden node. The accuracy stopped improving since then all the way to end of the experient with 200 hidden node. This suggests that having too many nodes does not neccessarily produce better output. On the other hand, the additional layer improved the accuracy from 70% to 85%. This suggests that having an additional layer improve the outcome when the task demands a model with more complexity. 

Lastly, the convulution model produced the best outcome of 94% consistently after some fine tuning. The fine tunning involves increasing the momentum to 0.9 and increasing the output channel of the convolution layers. This model started with a 90% accuracy at the 1st epoch and reached an accuracy of 94% at the 5th epoch. It was believed that the two convultion layers were the major factor of this accuracy, because it produced 4800 nodes as the output to the fully connect layer. An additional fully connected layer was also used as the 4th layer since it was allowed by the specification. Such structure  enchances the depth and capabilitiy of the model, making it satisfies the complexity demand of the task. Details of this fine tuning process will be further discussed in 4.c.

4.b 

The confusion matrix of the three models are listed below. Please find better formatted the output of each code section. The number on diagonal line from top left to bottom right indicates the correctly predicated character. Others are incorrectly predicated. It is found the 3rd row "su" す and the 7th row "ma" ま of the predication were most mistaken.  "ha" は and "ma" were mistakened as "su". "ki" き and "re" れ were mistakened as "ma". After reading Hiragana table, it was found "su" "ma" and "ha" all have a circle in the writting. "ma" "ki"  and "re" all two horizontal and one vertical strokes. These common features are likely to be more difficulty for a model to differentiate in different characters. 

Linear

[[766.   7.   8.   4.  59.   8.   5.  16.  11.   8.]

 [  5. 667.  60.  40.  51.  27.  21.  29.  36.  51.]
 
 [ 10. 107. 688.  57.  79. 119. 144.  25.  95.  86.]
 
 [ 12.  18.  27. 755.  22.  17.  10.  12.  38.   3.]
 
 [ 29.  31.  27.  16. 623.  19.  26.  86.   8.  54.]
 
 [ 64.  23.  20.  59.  21. 728.  25.  17.  30.  32.]
 
 [  2.  57.  46.  13.  33.  29. 723.  53.  45.  19.]
 
 [ 63.  15.  38.  17.  35.   8.  20. 623.   7.  30.]
 
 [ 31.  25.  47.  28.  20.  33.  11.  90. 706.  39.]
 
 [ 18.  50.  39.  11.  57.  12.  15.  49.  24. 678.]]

Test set: Average loss: 1.0085, Accuracy: 6957/10000 (70%)

Full

[[853.   7.   8.   3.  43.   5.   3.  17.  10.   1.]

[  5. 818.  13.   9.  36.  11.  14.  12.  28.  20.]

[  3.  32. 835.  33.  21.  66.  47.  14.  26.  46.]

[  6.   2.  36. 914.   4.  10.  10.   3.  45.   4.]

[ 26.  23.  12.   1. 799.  14.  17.  27.   2.  29.]

[ 27.  10.  20.  18.   9. 852.   7.  11.   8.   5.]

[  2.  56.  29.   3.  30.  16. 888.  37.  28.  12.]

[ 41.   4.  10.   2.  18.   2.   4. 819.   3.  21.]

[ 30.  17.  20.   7.  20.  15.   3.  27. 843.   8.]

[  7.  31.  17.  10.  20.   9.   7.  33.   7. 854.]]

Test set: Average loss: 0.5008, Accuracy: 8475/10000 (85%)

Convolution

[[949.   3.   8.   0.  12.   1.   3.   5.   3.   8.]

[  3. 929.   3.   2.   3.   2.   2.   2.  11.   7.]

[  3.   5. 905.  14.   3.  21.   8.   9.   7.  13.]

[  2.   1.  36. 974.  10.  13.   3.   2.  10.   4.]

[ 25.   4.   8.   0. 935.   4.   9.   2.  10.   5.]

[  2.   5.   8.   0.   9. 932.   2.   1.   2.   1.]

[  0.  34.  13.   6.  11.  14. 967.  12.   5.   4.]

[ 10.   2.   4.   2.   4.   1.   1. 953.   1.   2.]

[  6.   8.   7.   1.   9.   5.   2.   5. 951.   8.]

[  0.   9.   8.   1.   4.   7.   3.   9.   0. 948.]]

Test set: Average loss: 0.3493, Accuracy: 9443/10000 (94%)

4.c

The parameters adjusted for this task include learning rate, momentum and the output channels of the convolution layers. The structures of the model was also experiented with additional max pooling layer and fully connected layer.

The optimal learning rate and momentum was found at 0.01 and 0.9 respectively. Which is consistent to the excercise solution releeased prior to this assignment. The fluctations within the loss function between epochs was dealt with increased momentum. The default value would struggle to reach 90% accuracy. By setting the momentus high, the model moved much faster to achieve a high accuracy of 90% in the first epoch. The learning rate was kept at 0.01 because a higher value would make the learning process more violatile. 

Several articles on number recognition were read as references prior doing this task. In comparison, Japanese characters are found to be more complex than numerical numbers because they have more strokes. It was also found that the number of output channel in a convolution layer is related with the depth of deature maps. Hence, it was increased. This resulted in the number of nodes at the first fully connected were at a high 4800. In an effort to make the model more efficient, the output channel were reduced by half as an experiment, resulting in half the node at 2400. The resulting accuracy would be at 91%. Hence this indicates it is required to have this amount of node to meet the demanded complexity of the task. Max pooling was also added to the convolution layer with a similar lowered accuracy at 90% as results. This indicates while max pooling reduces the sample size, the assumption it allows the model to make neglects the differentiting features in characters.

Lastly as previously elaborate in 4.a, an additional fully connected layer was also used as the 4th layer since it was allowed by the specification. It was done because the accuracy would also be lowered to below 90%. It showed that it was not optimal to have 4800 node converge to 10 output nodes in one layer. 

In summary, the complexity of the nn model has to meet the complexity of the task. This is reflected in the parameters and structure set for the model. Generally speaking, more discreet tasks require more nodes and layers and attention to the depth of features. 





In [4]:
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import sklearn.metrics as metrics
import numpy as np
from torchvision import datasets, transforms
from kuzu import NetLin, NetFull, NetConv

def train(args, model, device, train_loader, optimizer, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()        
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % 100 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))

def test(args, model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    conf_matrix = np.zeros((10,10)) # initialize confusion matrix
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            # sum up batch loss
            test_loss += F.nll_loss(output, target, reduction='sum').item()
            # get the index of the max log-probability
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
            conf_matrix = conf_matrix + metrics.confusion_matrix(
                          pred.cpu(), target.cpu(), labels=[0,1,2,3,4,5,6,7,8,9])
        np.set_printoptions(precision=4, suppress=True)
        print(type(conf_matrix))
        print(conf_matrix)

    test_loss /= len(test_loader.dataset)

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))

# kuzu.py
# COMP9444, CSE, UNSW
class NetLin(nn.Module):
    # linear function followed by log_softmax
    def __init__(self):
        super(NetLin, self).__init__()
        # INSERT CODE HERE
        # define structure of the network here
        self.fc = nn.Linear(784, 10)
        
    def forward(self, x):
        # apply network and return output
        x = x.view(x.shape[0], -1)
        output = self.fc(x)
        probs = F.log_softmax(output)
        return probs # CHANGE CODE HERE


In [5]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
# Fetch and load the training data
trainset = datasets.KMNIST(root='./data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=False)

# Fetch and load the test data
testset = datasets.KMNIST(root='./data', train=False, download=True, transform=transform)
test_loader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

In [7]:
device = 'cpu'
epochs = 10
lr = 0.01
mom = 0.5
args = ''

In [118]:
# python3 kuzu_main.py --net lin
net = NetLin().to(device)

if list(net.parameters()):
    optimizer = optim.SGD(net.parameters(), lr=lr, momentum=mom)

    for epoch in range(1, epochs + 1):
        train(args, net, device, train_loader, optimizer, epoch)
        test(args, net, device, test_loader)

<generator object Module.parameters at 0x000001F982DA4AC8>


F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:69: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


Train Epoch: 1 [0/60000 (0%)]	Loss: 2.428725
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.008494
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.806207
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.812817
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.438675
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.649732
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.706801
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.714517
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.452791
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.739888
<class 'numpy.ndarray'>
[[732.   3.   6.   4.  67.   8.   4.  16.  11.   7.]
 [  4. 629.  62.  38.  40.  33.  16.  25.  34.  56.]
 [  9. 130. 671.  70.  85. 150. 151.  26.  92.  84.]
 [ 15.  18.  32. 729.  20.  19.  14.  19.  45.   3.]
 [ 32.  31.  25.  15. 618.  27.  29. 102.  10.  71.]
 [ 71.  20.  19.  53.  18. 691.  24.  16.  40.  26.]
 [  2.  71.  56.  13.  34.  29. 722.  70.  44.  20.]
 [ 78.  16.  40.  21.  29.   7.  21. 554.   9.  27.]
 [ 31.  25.  44.  44.  21.  27.   9. 113. 686.  46.]
 [ 26

In [124]:
# python3 kuzu_main.py --net full
hidden_node = 10
#device = 'cuda'

class NetFull(nn.Module):
    # two fully connected tanh layers followed by log softmax
    def __init__(self):
        super(NetFull, self).__init__()
        # INSERT CODE HERE
        global hidden_node
        self.fc1 = nn.Linear(784, hidden_node)
        self.fc2 = nn.Linear(hidden_node, 10)

    def forward(self, x):
        x = x.view(x.shape[0], -1)
        to_hidden = F.tanh(self.fc1(x))
        output = self.fc2(to_hidden)
        probs = F.log_softmax(output)
        return probs # CHANGE CODE HERE

for i in range(1, 20):
    hidden_node = 10 * i
    print('==== hidden_node is ', hidden_node, '====')
    
    net = NetFull().to(device)
    if list(net.parameters()):
        optimizer = optim.SGD(net.parameters(), lr=lr, momentum=mom)

        for epoch in range(1, epochs + 1):
            train(args, net, device, train_loader, optimizer, epoch)
            test(args, net, device, test_loader)

==== hidden_node is  10 ====


F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


Train Epoch: 1 [0/60000 (0%)]	Loss: 2.275897
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.694526
Train Epoch: 1 [12800/60000 (21%)]	Loss: 1.427657
Train Epoch: 1 [19200/60000 (32%)]	Loss: 1.250738
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.895856
Train Epoch: 1 [32000/60000 (53%)]	Loss: 1.027790
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.967641
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.929479
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.748270
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.870990
<class 'numpy.ndarray'>
[[745.   2.  10.   3.  92.   8.   4.  27.  10.  16.]
 [ 22. 593.  92.  84.  40.  57.  22.  10.  43.  47.]
 [  1. 162. 579.  36.  83. 218. 155.  53.  88. 109.]
 [  4.   9.  11. 597.  34.  48.  15.  19.  33.   3.]
 [ 24.  41.  19.  12. 596.  18.  42. 177.   7.  65.]
 [ 62.   6.  16.  97.   7. 484.   9.   8.  22.   7.]
 [  4.  68. 100.  16.  32.  34. 702.  76.  40.  16.]
 [ 41.   6.  26.  25.  23.  18.  20. 462.   6.  19.]
 [ 46.  28.  59.  88.  36.  99.  27. 130. 731.  68.]
 [ 51

 [ 16.  44.  22.  13.  44.   9.  15.  55.   8. 725.]]

Test set: Average loss: 0.8620, Accuracy: 7338/10000 (73%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.669838
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.636019
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.509507
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.456612
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.205659
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.443393
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.437810
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.477407
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.295614
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.498772
<class 'numpy.ndarray'>
[[775.   6.   5.   9.  71.   6.   5.   9.   8.   8.]
 [  5. 727.  58.  39.  59.  24.  29.  10.  36.  55.]
 [  3.  62. 714.  42.  58. 119. 102.  21.  23.  49.]
 [  9.  10.  30. 801.  16.  13.   5.  11.  38.   4.]
 [ 35.  24.  24.  12. 645.  17.  23.  77.   4.  62.]
 [ 56.  21.  19.  35.   6. 756.  24.  16.  29.  19.]
 [  1.  81.  50.  10.  36.  30. 777.  53.  35.  1

 [ 10.  33.  23.   8.  28.   7.   4.  39.   5. 782.]]

Test set: Average loss: 0.7068, Accuracy: 7843/10000 (78%)

==== hidden_node is  40 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.315551
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.397546
Train Epoch: 1 [12800/60000 (21%)]	Loss: 1.086494
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.897405
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.566534
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.764308
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.735538
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.714882
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.486570
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.709395
<class 'numpy.ndarray'>
[[769.   4.   5.   6.  83.   9.   6.  19.  11.   7.]
 [  7. 674.  73.  50.  48.  54.  26.  21.  44.  55.]
 [  6. 111. 665.  54.  75. 171. 155.  26.  68.  92.]
 [  5.  17.  34. 743.  18.  23.  13.  10.  42.   2.]
 [ 29.  29.  20.  15. 624.  19.  25. 127.   7.  70.]
 [ 46.   9.  11.  40.  10. 638.   9.  11.  31.   9.]
 [  3.  66.  56.  12

 [ 11.  39.  22.   7.  42.   4.   9.  48.   9. 758.]]

Test set: Average loss: 0.7213, Accuracy: 7754/10000 (78%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.471140
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.439184
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.404038
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.322328
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.155012
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.415001
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.371159
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.421127
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.184727
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.372473
<class 'numpy.ndarray'>
[[832.   5.   7.   3.  65.  11.   4.   9.  10.   5.]
 [  3. 758.  30.  21.  41.  16.  18.  10.  42.  26.]
 [  1.  45. 795.  38.  37. 113. 103.  23.  33.  73.]
 [ 10.   7.  28. 877.  11.  15.   9.   4.  47.   2.]
 [ 23.  26.  18.   5. 713.  15.  21.  48.   6.  48.]
 [ 26.  13.   9.  24.  12. 769.   9.  10.  14.  13.]
 [  3.  74.  44.   8.  34.  31. 809.  68.  31.  2

 [  6.  28.  13.   7.  25.  15.   9.  33.   8. 809.]]

Test set: Average loss: 0.5854, Accuracy: 8217/10000 (82%)

==== hidden_node is  70 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.274899
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.350972
Train Epoch: 1 [12800/60000 (21%)]	Loss: 1.027614
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.864319
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.487235
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.728091
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.712900
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.696298
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.450319
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.684950
<class 'numpy.ndarray'>
[[752.   6.   7.   5.  74.  10.   3.  15.  10.   4.]
 [  3. 644.  60.  34.  45.  30.  16.  25.  39.  58.]
 [  5. 121. 700.  67.  87. 150. 164.  26.  66.  89.]
 [  9.  16.  38. 760.  17.  25.  14.  15.  50.   2.]
 [ 26.  31.  21.  12. 620.  20.  31.  93.   5.  62.]
 [ 62.  14.  13.  47.  10. 693.  12.  12.  36.  18.]
 [  2.  87.  56.  13

 [  9.  29.  17.  12.  31.   7.   7.  42.   6. 775.]]

Test set: Average loss: 0.6640, Accuracy: 7964/10000 (80%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.403411
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.381262
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.367543
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.312811
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.154020
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.357164
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.322526
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.433598
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.183301
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.372919
<class 'numpy.ndarray'>
[[834.   5.   6.   4.  57.  11.   4.  12.  12.   3.]
 [  3. 764.  17.  15.  42.  16.  13.  21.  34.  29.]
 [  1.  40. 818.  49.  29.  71.  89.  22.  39.  58.]
 [  7.   9.  42. 883.  12.  16.  11.   9.  48.   4.]
 [ 31.  24.  14.   3. 745.  13.  15.  40.   4.  39.]
 [ 41.   9.  14.  16.  11. 814.   7.   8.  15.  10.]
 [  3.  78.  35.   4.  31.  27. 841.  45.  30.  3

 [  5.  38.  13.   8.  19.   4.   7.  34.   8. 839.]]

Test set: Average loss: 0.5361, Accuracy: 8346/10000 (83%)

==== hidden_node is  100 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.367243
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.306484
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.992468
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.865820
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.495794
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.701958
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.705650
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.654756
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.429570
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.671810
<class 'numpy.ndarray'>
[[782.   4.   7.   6.  81.  10.   6.  18.   9.   6.]
 [  3. 649.  63.  39.  42.  30.  15.  22.  40.  53.]
 [  3. 113. 676.  55.  75. 142. 153.  23.  68.  83.]
 [  9.  15.  40. 773.  17.  23.  11.  18.  41.   3.]
 [ 26.  30.  21.  14. 631.  22.  29. 103.   5.  68.]
 [ 46.  15.  15.  35.  14. 694.  15.  13.  36.  15.]
 [  3.  85.  56.  1

 [  7.  35.  21.   9.  30.   6.  13.  45.  10. 784.]]

Test set: Average loss: 0.6532, Accuracy: 7988/10000 (80%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.451315
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.385031
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.336947
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.312691
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.171821
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.341057
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.308639
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.446374
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.182729
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.361092
<class 'numpy.ndarray'>
[[833.   5.   9.   4.  55.  11.   4.  16.   9.   5.]
 [  3. 784.  19.  13.  34.  17.  13.  15.  30.  21.]
 [  1.  39. 801.  44.  25.  89.  78.  22.  30.  67.]
 [  8.   5.  38. 894.  14.  13.   6.   4.  51.   1.]
 [ 30.  23.  13.   4. 770.  14.  26.  40.   6.  43.]
 [ 33.  14.  19.  14.   7. 794.   6.   9.  11.   7.]
 [  3.  67.  37.   3.  34.  32. 845.  33.  36.  2

 [  7.  25.  17.  13.  21.   9.   7.  38.  10. 853.]]

Test set: Average loss: 0.5209, Accuracy: 8456/10000 (85%)

==== hidden_node is  130 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.250802
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.270112
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.981063
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.838731
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.473805
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.711379
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.688505
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.662672
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.405125
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.689292
<class 'numpy.ndarray'>
[[764.   4.   7.   7.  80.   8.   4.  17.  10.   5.]
 [  4. 656.  66.  36.  38.  39.  20.  17.  38.  56.]
 [  5. 113. 686.  62.  81. 148. 144.  21.  77.  84.]
 [ 11.  14.  40. 763.  22.  19.  14.  16.  50.   2.]
 [ 28.  38.  22.  15. 626.  25.  25.  99.   7.  67.]
 [ 59.  13.  12.  38.  14. 696.  19.  12.  36.  22.]
 [  2.  83.  58.  1

 [  9.  30.  25.   8.  25.   7.   6.  40.   8. 797.]]

Test set: Average loss: 0.6381, Accuracy: 8018/10000 (80%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.420623
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.379246
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.346063
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.292722
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.160619
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.330625
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.333292
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.422103
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.186970
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.396228
<class 'numpy.ndarray'>
[[829.   7.   8.   4.  56.  12.   4.  22.  12.   4.]
 [  2. 789.  17.  14.  28.  13.  17.  16.  31.  27.]
 [  2.  41. 807.  35.  22.  79.  73.  15.  26.  56.]
 [  9.   7.  41. 904.  10.  11.   8.   8.  53.   5.]
 [ 27.  22.  12.   3. 774.  15.  19.  33.   5.  33.]
 [ 36.  10.  19.  13.  10. 812.   7.  12.  15.   6.]
 [  5.  67.  38.  10.  36.  30. 858.  47.  33.  2

 [  7.  33.  14.  15.  14.   8.   6.  35.   7. 839.]]

Test set: Average loss: 0.5119, Accuracy: 8431/10000 (84%)

==== hidden_node is  160 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.375343
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.236374
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.955738
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.835077
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.451891
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.696840
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.674787
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.685344
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.428080
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.730385
<class 'numpy.ndarray'>
[[754.   3.   7.   6.  79.   9.   5.  14.  11.   5.]
 [  5. 656.  60.  39.  41.  42.  20.  26.  43.  52.]
 [  6. 111. 680.  60.  83. 153. 152.  24.  82.  83.]
 [ 13.  17.  41. 759.  17.  23.  12.  17.  46.   2.]
 [ 28.  34.  23.  17. 626.  21.  26. 108.   6.  70.]
 [ 59.  16.  12.  36.  14. 675.  18.  12.  32.  13.]
 [  3.  83.  64.  1

 [  8.  32.  21.   8.  31.   6.   9.  41.   8. 767.]]

Test set: Average loss: 0.6571, Accuracy: 7927/10000 (79%)

Train Epoch: 6 [0/60000 (0%)]	Loss: 0.452697
Train Epoch: 6 [6400/60000 (11%)]	Loss: 0.377238
Train Epoch: 6 [12800/60000 (21%)]	Loss: 0.345376
Train Epoch: 6 [19200/60000 (32%)]	Loss: 0.303353
Train Epoch: 6 [25600/60000 (43%)]	Loss: 0.145615
Train Epoch: 6 [32000/60000 (53%)]	Loss: 0.334400
Train Epoch: 6 [38400/60000 (64%)]	Loss: 0.326577
Train Epoch: 6 [44800/60000 (75%)]	Loss: 0.397287
Train Epoch: 6 [51200/60000 (85%)]	Loss: 0.173851
Train Epoch: 6 [57600/60000 (96%)]	Loss: 0.391690
<class 'numpy.ndarray'>
[[828.   4.   7.   5.  52.  10.   4.  22.   9.   7.]
 [  4. 792.  25.  14.  37.  21.  17.  12.  32.  28.]
 [  3.  38. 809.  39.  27.  94.  76.  23.  30.  72.]
 [  5.   7.  41. 890.  11.  15.  11.   5.  55.   6.]
 [ 30.  25.  12.   2. 755.  12.  18.  28.   5.  41.]
 [ 38.  13.  17.  20.  12. 788.   9.  10.  13.   6.]
 [  4.  65.  38.   9.  39.  30. 846.  41.  34.  2

 [  5.  24.  11.  10.  17.   6.   7.  34.   4. 834.]]

Test set: Average loss: 0.5047, Accuracy: 8442/10000 (84%)

==== hidden_node is  190 ====
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.336677
Train Epoch: 1 [6400/60000 (11%)]	Loss: 1.225528
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.931678
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.840454
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.453163
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.703618
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.711378
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.672705
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.418968
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.709479
<class 'numpy.ndarray'>
[[756.   4.   7.   5.  73.  10.   5.  16.   7.   5.]
 [  4. 646.  61.  41.  47.  30.  22.  26.  42.  54.]
 [  6. 116. 686.  60.  77. 144. 144.  26.  83.  87.]
 [ 11.  16.  41. 762.  20.  19.  13.  16.  50.   2.]
 [ 29.  33.  21.  17. 626.  22.  24. 100.   8.  69.]
 [ 60.  18.  15.  39.  13. 707.  17.  16.  38.  25.]
 [  4.  81.  53.  1

In [14]:
# torch.cuda.get_device_name(0)

# https://stats.stackexchange.com/questions/380996/convolutional-network-how-to-choose-output-channels-number-stride-and-padding
# depth of feature maps https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html?highlight=channels%20conv2d
# https://nextjournal.com/gkoehler/pytorch-mnist
class NetConv(nn.Module):
    # two convolutional layers and one fully connected layer,
    # all using relu, followed by log_softmax
    def __init__(self):
        super(NetConv, self).__init__()
        # INSERT CODE HERE
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 12, 5)
        self.fc1 = nn.Linear(4800, 400)
        self.fc2 = nn.Linear(400, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        #print(x.shape)
        
        x = x.view(x.shape[0], 4800)
        
        #print(x.shape)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        #print(x.shape)
        probs = F.log_softmax(x)
        return probs # CHANGE CODE HERE
    
net = NetConv().to(device)
mom = 0.9
lr = 0.01
if list(net.parameters()):
    optimizer = optim.SGD(net.parameters(), lr=lr, momentum=mom)

    for epoch in range(1, epochs + 1):
        train(args, net, device, train_loader, optimizer, epoch)
        test(args, net, device, test_loader)

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.


Train Epoch: 1 [0/60000 (0%)]	Loss: 2.296162
Train Epoch: 1 [6400/60000 (11%)]	Loss: 0.690401
Train Epoch: 1 [12800/60000 (21%)]	Loss: 0.420182
Train Epoch: 1 [19200/60000 (32%)]	Loss: 0.397262
Train Epoch: 1 [25600/60000 (43%)]	Loss: 0.158494
Train Epoch: 1 [32000/60000 (53%)]	Loss: 0.335701
Train Epoch: 1 [38400/60000 (64%)]	Loss: 0.263214
Train Epoch: 1 [44800/60000 (75%)]	Loss: 0.325325
Train Epoch: 1 [51200/60000 (85%)]	Loss: 0.070242
Train Epoch: 1 [57600/60000 (96%)]	Loss: 0.161246
<class 'numpy.ndarray'>
[[928.   4.   7.   4.  23.   5.   4.   7.  19.  10.]
 [  2. 892.   2.   2.  13.   9.   9.   8.  14.   4.]
 [  3.  12. 863.  26.   8.  75.  25.  15.   6.  18.]
 [  0.   2.  33. 927.  10.   8.   3.   0.  12.   5.]
 [ 47.  11.  15.   2. 903.   6.   6.  20.  16.  21.]
 [  8.   5.  12.  22.   2. 854.   7.   0.   4.   7.]
 [  1.  52.  36.   7.  20.  32. 941.  25.   8.  15.]
 [  7.   2.   1.   2.   1.   0.   1. 873.   0.   3.]
 [  1.   7.  15.   5.  16.   8.   3.  22. 919.  21.]
 [  3